### ISSUE TITLE
Consider a 'resolved' option for block

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#16]
Currently, to clean up clutter of done work the only option is to entirely delete the editorial block. However, for evaluation purposes it seems like marking it as 'resolved' to hide it, but still make it available for end-of-semester evaluation might make sense. 

Problem will be how to signal whether to show the 'resolved' stuff.

**Comment by sheilabrennan** [comment]
While I think this is a great idea to create a 'resolved' state of content blocks, I don't think we can do that with the exhibit builder. We will have to rely on instructors to duly note the responses they receive in this digital space. And then they can delete them when they are finished with the feedback.
