### ISSUE TITLE
First run-through of Editorial testing

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#22]
This one get complicated on a couple levels. Beyond just making sure it installs on other servers, we're looking at a lot of human interaction stuff, since it is designed to be analogous to margin comments on a paper, but here the comments are on an Exhibit Page, and there are threaded responses to the original comment. Thus, some role-playing (teacher and students) will be helpful to get into the UX of how it works.

**Installation**
Use the current master branch of Editorial, AND use the current master of ExhibitBuilder

**Testing**

For an Exhibit-in-progress, go to edit a page. There's a new block called 'Editorial'. Create one of those, and leave a comment. Also, add users to the allowed access list within the options for the block. Save the page. Then you should also be able to send email notifications to the allowed users, with optional additional text for the email.

Those users should then be able to access the page and add threaded comments to the original comment. Users who have not been given access should have no access to the block, unless they are admins or supers. That should be true on both the admin and public sides

Feedback on those mechanics is the starting point, but as always UX and UI thoughts are welcome!

**Comment by mebrett** [comment]
@alyssafahringer @jannellelegg We'll test this on my dev install of Classic (Very Large Sandbox)

**Comment by alyssafahringer** [comment]
When testing, unable to see editorial blocks @mebrett created within her exhibit. When @jannellelegg created a block, able to view and comment only if an email was sent alerting her that a response was posted. Otherwise I got the following error: 
![screen shot 2016-09-12 at 12 35 38 pm](https://cloud.githubusercontent.com/assets/8807816/18444261/7d36cc42-78e6-11e6-9f55-22c65c119682.png)

**Comment by mebrett** [comment]
Jannellle and Alyssa are admins on the site

**Comment by patrickmj** [comment]
@alyssafahringer If the full stack trace is there, could you paste it up? 
Probably that should be a new issue so everything doesn't pile up in comments on this issue

**Comment by patrickmj** [comment]
@mebrett I think this is fixed on the latest master.

You'll have to uninstall the plugin to clear out the crap data, then install the latest master.

**Comment by patrickmj** [comment]
@mebrett variety of bugs found, including the uninstall issue #24 should be fixed, so hopefully we can start this back up. Pulling in latest master before uninstalling should make the uninstall work.

**Comment by mebrett** [comment]
Did not work on Omeka core branch master but did when I dialed back to branch stable-2.4

**Comment by patrickmj** [comment]
Did not work as in didn't install, or something else?

**Comment by mebrett** [comment]
Uninstalling did not stick until I moved my install from master to stable2-.4

**Comment by patrickmj** [comment]
Hmm...I suspect I know what might have happened, especially if you uninstalled using the older version of Editorial instead of the new stuff on master I pushed up this morning.

There was a problem where the uninstall of Editorial would fail deleting its own page blocks where it'd delete 1 of its blocks, then silently fail. That's what makes the uninstall not stick. But, running the uninstall multiple times deletes its own blocks one at a time until they are all gone. So, I'm guessing that it was a coincidence that reverting core to 2.4, then uninstalling again, got through all the blocks to delete and finally stuck with the uninstall.

So, try bumping back up to Omeka master, grabbing the latest Editorial master, and see what happens.

**Comment by mebrett** [comment]
Pulled from master on the core and the uninstall worked fine (I was already on the latest of Editorial).
