### ISSUE TITLE
Plugin doesn't uninstall

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Editorial#24]
When going through the steps to updated to latest commit, I found that uninstalling doesn't seem to work. After clicking the checkbox to confirm uninstall, I'm redirected back to plugins and Editorial has the options to Activate and Uninstall. 
![screen shot 2016-09-14 at 10 07 16 am](https://cloud.githubusercontent.com/assets/2314070/18515439/57a50894-7a63-11e6-8d1b-0e456c712dcc.png)

**Comment by patrickmj** [comment]
ah...sorry. forgot about that detail. It's fixed in the newer version. You just need to hit uninstall a bunch of times until it takes. Should be once for every editorial block that was created.

**Comment by patrickmj** [comment]
plus, i found a new bug with the new version, so okay to hold off on this

**Comment by mebrett** [comment]
Okay, just let me know when it's safe to try again.
