### ISSUE TITLE
Grant Access/Email Recipient issue 

### ISSUE THREAD

**Issue by jannellelegg** [omeka/plugin-Editorial#29]
When creating a new comment possible recipients are not included in the list (only original commenter), before and after access has been granted to other users.

![screen shot 2016-09-28 at 12 19 31 pm](https://cloud.githubusercontent.com/assets/5897725/18923022/d48b8354-8578-11e6-86e8-550e6ead9e50.png)

After an initial comment is made, users that have been granted access are included as possible recipients, and after you grant access to additional users, their name will be added to the list of possible recipients.

![screen shot 2016-09-28 at 12 26 19 pm](https://cloud.githubusercontent.com/assets/5897725/18923023/d48c041e-8578-11e6-9f03-a81b1b182147.png)

As an aside, the order of operations may need to be adjusted or helper text added to indicate that users that are granted access after the commenter has selected recipients for email (see image 2), they are not automatically included as recipients. Perhaps if the granting access block appeared first, users would be able to select from a complete list of possible recipients that have been granted access?

**Comment by patrickmj** [comment]
good catch. thanks!
