### ISSUE TITLE
Updates for testing

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#30]
Latest master branch should address #26 #27 #28 #29 

For the deleting in #27, this might get sticky, because we know from many forum posts that teachers get concerned about who can edit and delete what. In this system, deleting a response deletes all it's child responses. That seems in order, but it's possible that additional check could/should happen. Then again, that's a tech solution to a social problem, so I'm ambivalent about the approach. 

So, updating the code to latest master and seeing if it addresses the above issues looks like the next step. 
Thanks!

**Comment by mebrett** [comment]
@jannellelegg @alyssafahringer we'll look at this Monday.
