### ISSUE TITLE
Public view: "Call to a member function exists() on null"

### ISSUE THREAD

**Issue by kimisgold** [omeka/plugin-Editorial#31]
I installed the Editorial plugin and added an Editorial block on the admin side. On the public side, I received this error where I expected the Editorial content to appear:

`Fatal error: Call to a member function exists() on null in /Users/kim/Sites/omeka/plugins/Editorial/EditorialPlugin.php on line 326`

**Comment by zerocrates** [comment]
this is a very deep and philosophical error message

**Comment by patrickmj** [comment]
Editorial requires the latest master of Exhibit Builder. If this is on your install, make sure that's up to date

Otherwise, it should probably return 'Nietzsche'.

**Comment by kimisgold** [comment]
Yup, updating ExhibitBuilder fixed it.
