### ISSUE TITLE
Changing user role breaks plugin

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Editorial#32]
I had @jannellelegg set as Admin and she had made an editorial block on an Exhibit Page. To check user role application, I dropped her down to exhibit-contributor and the block which she created is now throwing an error and preventing the Add New Block options from appearing.

<img width="734" alt="screen shot 2016-10-05 at 11 30 35 am" src="https://cloud.githubusercontent.com/assets/2314070/19119892/396fc9c6-8aef-11e6-8bdb-44127fda088c.png">

Error is: `Fatal error: Call to a member function getOwner() on null in /websites/omekadev/home/www/mebrett/Omeka/plugins/Editorial/models/Table/EditorialBlockOwner.php on line 26`

**Comment by mebrett** [comment]
For the record, even though the block has a delete X, it doesn't work. I think the only way to fix it at this point would be either to uninstall the plugin or completely delete the page.

**Comment by patrickmj** [comment]
Could you narrow down the circumstances and path to reproduce the issue of the delete X not working? This sounds like it might be  a distinct issue.

**Comment by jannellelegg** [comment]
I think my user status was changed in the midst of a save. The problem doesn't seem to be occurring on other pages.

**Comment by patrickmj** [comment]
Sounds like I'll need to look at what's stored (or not) in the database. Which site is this happening on?

**Comment by mebrett** [comment]
http://dev.omeka.org/mebrett/Omeka/admin/exhibits/edit-page/59 specifically, http://dev.omeka.org/mebrett/Omeka/admin/exhibits/edit/44 is where we're testing more broadly
(Patrick, you have a user account, admin level)

**Comment by patrickmj** [comment]
There's lots in play, but, especially from @mebrett's observations, it might be an artifact of the previous problems related to EB version issue (that's not certain, but possible from what I see). If you uninstall and reinstall Editorial, with EB on current master, does that make things better when running through these scenarios?
