### ISSUE TITLE
Cannot delete an editorial block that is throwing an error

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Editorial#33]
When an Editorial block throws an error, it prevents anything from showing below it (additional blocks or the Add New Block option) and cannot be deleted. 
<img width="734" alt="screen shot 2016-10-05 at 11 30 35 am" src="https://cloud.githubusercontent.com/assets/2314070/19123308/19e28f5a-8afc-11e6-8b47-4eb390ca8748.png">

Further, none of the blocks on that page can be deleted or collapsed. 
This is related to #32 but I suspect is true for whenever the Editorial block breaks throwing an error. In the past, a broken block has prevented anything from loading beneath it.

**Comment by mebrett** [comment]
Example http://dev.omeka.org/mebrett/Omeka/admin/exhibits/edit-page/59

**Comment by mebrett** [comment]
I was able to create another broken block by adding an exhibit-contributor user to a block, logging out. I logged back in as that user and went to the page with that editorial block. Page broke. 

<img width="573" alt="screen shot 2016-10-05 at 2 29 24 pm" src="https://cloud.githubusercontent.com/assets/2314070/19126708/fd98a330-8b09-11e6-86be-8e86e3e361c6.png">

**Comment by patrickmj** [comment]
I'm pushing up new code to address these, but it sound like we're finding bugs. Not sure if, after all, we're ready to release or have others look at it. This is a problem.
