### ISSUE TITLE
Editorial block options stored on other blocks

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#35]
On second save of a page with an editorial block, the options for it also get saved onto other, non-editorial blocks.

**Comment by patrickmj** [comment]
This appears to only happen on 'text' blocks. Interestingly, depending on the order of the blocks, EB blocks like 'file-text' also seem to get their data bled onto 'text' blocks. @zerocrates have you seen this behavior? It doesn't seem to break anything, just puts oddities in the database.

**Comment by zerocrates** [comment]
I'm not sure I understand what's happening here. Can you describe in more detail?

**Comment by patrickmj** [comment]
Just confirmed this with Editorial deactivated, so I figure makes sense to move fuller description over to an EB issue
