### ISSUE TITLE
Second Round of Testing

### ISSUE THREAD

**Issue by jannellelegg** [omeka/plugin-Editorial#36]
Three areas of testing needed: 

**User commenting:** 

EC, C, Admin, Super create a new comment block on a page and initiate a chain of three or more comments (EC, C, Admin, Super)
- confirm visibility of comments on back end
- confirm visibility of comments on front end
- confirm super, admin, contributor, exhibit-contributor can edit their own comments
- confirm super, admin can edit other comments, contributor, exhibit-contributor cannot
- confirm super, admin, contributor, exhibit-contributor can delete their own comments
- confirm super and admin can delete other comments, contributor, exhibit-contributor cannot

**Editorial block errors (issue #33 )** 
- if errors appear on the page, confirm that the block can be deleted or collapsed
- if errors appear on the page, confirm that other blocks on the page can be deleted or collapsed.

**Change user role (issue #32 )**
- confirm super, admin, contributor, exhibit-contributor can be modified and previous comment pages are still functioning.

**Comment by jannellelegg** [comment]
@mebrett @alyssafahringer

**Comment by jannellelegg** [comment]
EC Testing: 

Access:
- when at EC status, user cannot view back end of exhibits or items until added to a comment.
- when at EC status, user CAN add an exhibit, pages, items, and create comment chains in that exhibit.
- when at EC status, user can, after they have been granted access to exhibit, edit the exhibit pages. Cannot edit items.

Visibility:
- when at EC status, comments are visible on front end of public exhibit to which EC has access 
- when at EC status - cannot view comments made by other EC user (to which I have not been given access)

Commenting: 
- when replying  - respondent cannot modify the list of users with access - options panel only for emails.
- EC can edit comments, but cannot delete.

Note on Email content:
- initial emails (sent with comments) include original comment text, response to comment emails (sent by those leaving a reply) also include original comment text and not the reply text. 
- if additional text is added to the comment (drop down option) that text appears in the email as well as the original comment - but not the reply comment.

**Comment by patrickmj** [comment]
Many thanks! 

Most of that sounds like it is behaving as expected -- whether that's the most desirable behavior is an open question.

Access:
Those all sound right.

Visibility:
Same. Sounds like the access is working as designed. Again, though, whether a different design is in order is an open question.

Commenting:
- when replying. Hmmm.... if adding email recipients is there, but not access changes, that sounds like a good candidate to list as a distinct issue.
- editing and deleting: also sounds like a candidate for a distinct issue -- if someone can edit, they should be able the delete by erasing everything and saving the changes

Email content:
Sounds right by the design. Should give a snippet so receiver can see where the action is and go to it quickly.

**Comment by patrickmj** [comment]
From the original issue, do errors still exist on the page after uninstall/reinstall for #32 and #33? From what you're seeing, should those be closed?

**Comment by jannellelegg** [comment]
@patrickmj  - I haven't encountered the issue from #33 yet. @mebrett can we change my user status from EC to C and check for #32 tomorrow?

**Comment by jannellelegg** [comment]
Testing as an EC that was changed to Contributor- produced errors relating to issues #33 and #32 

**General behavior at C level:** 
Access:
- when at C status, user cannot view back end of exhibits or items until added to a comment.
- when at C status, user CAN add an exhibit, pages, items, and create comment chains in that exhibit.
- when at C status, user can, after they have been granted access to exhibit, edit the exhibit pages. Cannot edit items.

Visibility:
- when at C status, comments are visible on front end of a private exhibit to which C has access (note: time/date stamp is only visible on front end of exhibit)

Commenting:
- when replying - C cannot modify the list of users with access - options panel only for emails.
- C can edit comments, but cannot delete comments

**Behavior specific to a modified user status:**
- Modified user status changed user access to Exhibits (had access as EC, did not at C) except for an exhibit created as EC (still had access to the exhibit I created as EC)
- Attempted to visit an Exhibit page as C, that contained an Editorial block (initiated by Super User), that included comments I made at EC status (chain included the Super User and other EC). Block broke, blocks cannot be minimized or deleted. Page cannot be saved (buttons disappeared) and new blocks cannot be added (panel disappeared).

Screenshot of error message:
![screen shot 2016-10-12 at 2 22 55 pm](https://cloud.githubusercontent.com/assets/5897725/19322659/ebd0ee54-9087-11e6-96fd-1e9420c1ff72.png)

**Comment by alyssafahringer** [comment]
Received an email from @jannellelegg (level - C) with body in the text of the email. When I clicked the link in the email to access the page within the exhibit, I couldn't see any editorial blocks. Currently I am an EC. 
![screen shot 2016-10-12 at 2 33 26 pm](https://cloud.githubusercontent.com/assets/8807816/19322957/f4ba9b40-9088-11e6-806d-c94034770199.png)

**Comment by jannellelegg** [comment]
Ok, played with the settings regarding Alyssa's feedback.

It looks like this was an issue with granting access - in attempting to add the Super User to the comment thread, the EC no longer had access to the thread. 

Tested again and identified that user access to the entire thread (not just the most recent comment) could be toggled on and off by the creator of the thread. Even after I limited access to the thread to Super User, the comments previously made by the EC remained (ie: it didn't break.)

![screen shot 2016-10-12 at 2 35 33 pm](https://cloud.githubusercontent.com/assets/5897725/19323437/eb471eba-908a-11e6-9fb6-0b9f110555d1.png)

**Comment by patrickmj** [comment]
Much, but not all, of what's listed by @jannellelegg in https://github.com/omeka/plugin-Editorial/issues/36#issuecomment-253297302 is as expected. The EC role is basically a small step above Contributor, so switching someone from EC to C is basically a demotion, removing some access. At least that's what I _think_ should happen, but I'm testing things out now.

**Comment by patrickmj** [comment]
@jannellelegg @alyssafahringer For trying to recreate the email link issue above, could you add me to whatever site you're using (if I'm not already) and try to recreate the issue with me? Thanks.
