### ISSUE TITLE
Branch develop throwing Mysqli prepare error when saving changes

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Editorial#37]
Both after I tried to add a new editorial block and when I tried to uninstall the plugin (in case that was the issue) I got this error: 

```
exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Table 'omekadev.mrbOmeka1_editorial_block_infos' doesn't exist' in /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Db/Statement/Mysqli.php:77
```

Both actions work fine on master branch.

**Comment by patrickmj** [comment]
So, it uninstalled and reinstalled okay, but still threw this?

**Comment by mebrett** [comment]
it's working now. Apparently I had borked something somewhere along the lines - remove and reinstall worked.

**Comment by patrickmj** [comment]
Hooray!
