### ISSUE TITLE
Should users w/ access be able to add users?

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#40]
Via #36 

> when replying - C cannot modify the list of users with access - options panel only for emails.
> I'm not sure the C should have any access at all in this situation, but it looks like the same is true of EC user.

So, a question about access -- should only the owner of the original comment be able to add participants, or should any participant be able to add others? In the usual workflow/access concerns, I can see either way.

Thoughts, @jannellelegg @mebrett @alyssafahringer ?

**Comment by mebrett** [comment]
On the one hand, it would be useful to be able to invite people to the conversation, but that could also be accomplished by asking the admin/super/original commenter to add the person.

**Comment by sheilabrennan** [comment]
Only the original commenter should be able to add a participant.
