### ISSUE TITLE
Multiple contributors at the same time clobbers the system

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#41]
If multiple people start editing a block, when one person saves their comment the block ID will change. That means that the `old_id` data on other people's edit pages will no longer align with the database, which means great chain-effect breakage. (Where 'great' means 'hugely sucky')

**Comment by sheilabrennan** [comment]
This is an Omeka and Exhibit Builder problem, that doesn't seem fixable in this plugin. 

I totally understand why it is useful and helpful, and it brings up much bigger issues for the team to discuss for Omeka Classic as a whole. I don't think we can fix that here. 

The way we fix it is through documentation and advising instructors how to use this with their students.

**Comment by patrickmj** [comment]
At the least, I think we should figure out a way to flash a message that something went amiss. Ideally, we'll find a way to retain the data submitted, but lost. That's a hard ask, but worth pursuing.
