### ISSUE TITLE
Adding a comment to a second Editorial block on a page erases the first/reassigns attribution

### ISSUE THREAD

**Issue by jannellelegg** [omeka/plugin-Editorial#47]
Scenario:
User A creates an editorial block on a page, granting access to only User B. [Everything works appropriately: Both users are able to comment. The block is not visible to other users.]
User B creates an editorial block on the page, granting access to User C. [User B is able to comment on the block without issue. User C's comment is saved.]

Odd behavior:
When User C adds their comment to the second editorial block, the first block is deleted. The user names in the second block are changed so that User B's comment is attributed to User A. 

This seems to happen when User A is a Super User, but users B and C are either Contributor or Exhibit-Contributor. Problem does not seem to reproduce when User A is a Contributor/User B is an Exhibit-Contributor/ User C is a Researcher.

**Comment by patrickmj** [comment]
Partial confirmation with a simpler scenario:
A and B have created separate blocks. A responds to B. A's block gets reassigned to B.

Unclear whether fixing this simplified case will fix the more complex case above.
