### ISSUE TITLE
Response and Child boxes editable simultaneously

### ISSUE THREAD

**Issue by jannellelegg** [omeka/plugin-Editorial#48]
When Super User clicks to edit a response comment in a thread, the child reply field also editable. 

![screen shot 2017-01-31 at 11 08 05 am](https://cloud.githubusercontent.com/assets/5897725/22474099/f8a0c55a-e7a8-11e6-9c90-805a58ab4947.png)

**Comment by patrickmj** [comment]
This could lead us into complicated expectations. A Super can always edit anything, at least in most all of the rest of Omeka. It looks like a non-super or non-admin doesn't have the same capability (at least on develop branch as of now). If that's confirmed in next testing round, this might be another question that calls for more feedback about behavior?
