### ISSUE TITLE
Testing Round N+1

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#53]
On newest master of Editorial, and latest release of Omeka and ExhibitBuilder (should be basically same as last testing round). To clear out the bad data, you'll want to uninstall and reinstall Editorial for this testing.

This update should fix #47 and #48, so those will be the first things to check.

Bonus checks: Deleting. With a bunch of Editorial comments, with a good chain of responses, does deleting both individual blocks, and wholesale deleting of a page work? As before,the combo of many people being involved in the conversation is a significant factor. This relates to the undecided #50 and #10. So it'll just be info gathering on those for anything besides clear bugs.

@alyssafahringer wins the prize for me not being able to recreate #49! But if in this round there's any additional info you discover that sheds light on it, that is of course much appreciated. It might just be solved as a side-effect of the new changes, but ya never know.

Thanks

**Comment by jannellelegg** [comment]
This seems to be resolved. 
- Issue #47 : couldn't reproduce the editing issue. Editing multiple boxes on one save also worked.
- Issue #48 : ownership of editorial blocks didn't shift users and removing or editing permissions for a block owner was not possible. The comments made by user were not removed after their access was revoked.
- Issues #10  and #50 : deleting comments worked as expected. 

We were unable to reproduce the issue in #49 .
