### ISSUE TITLE
Quick test of emails

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#56]
@jannellelegg: Following #55, could I ask for a quick double-check just on the emailing -- messages still get to the right people. Just needs a pull of latest master.

(since emailing from a laptop dev environment doesn't work, this needs an installation on 'real' server to test)

**Comment by mebrett** [comment]
Emails don't seem to be sending, and for non-Superusers the options to send emails isn't even available: 

<img width="708" alt="screen shot 2017-02-20 at 2 41 08 pm" src="https://cloud.githubusercontent.com/assets/2314070/23139535/d6b8c9c4-f77a-11e6-9b00-47e43f1c0ad1.png">

In the above image, the direction of the arrow indicates that I *should* be seeing options but I am not - I am an exhibit-contributor on this installation

**Comment by patrickmj** [comment]
Latest master should fix this

**Comment by mebrett** [comment]
Commit 5ae538a does not seem to have resolved email issue. Admins can now see email options but Exhibit-contributors cannot.

**Comment by patrickmj** [comment]
well, poop. I never pushed up the changes. Apologies for the waste of time.

The actual changes are now up in github
