### ISSUE TITLE
Error deleted an Editorial Block from Exhibit

### ISSUE THREAD

**Issue by sheilabrennan** [omeka/plugin-Editorial#58]
I successfully added an Editorial block. I even re-ordered the blocks, and successfully saved. 

Then, after I saved my deletion of an editorial block, received this error, and I cannot do anything else on this page:
Fatal error: Call to a member function getOwner() on null in /websites/chnmdev/home/www/arthistorydev/omeka/plugins/Editorial/views/shared/exhibit_layouts/editorial-bl
![editorialdeletedblock](https://cloud.githubusercontent.com/assets/741484/23861831/a3c6529e-07e1-11e7-9746-27d4366ecea4.jpg)
ock/form.php on line 17

http://chnmdev.gmu.edu/arthistorydev/omeka/admin/exhibits/edit-page/14 

Today, I pulled the master of both Exhibit Builder and Editorial. I also deactivated and uninstalled Editorial, then reinstalled before trying this.

**Comment by patrickmj** [comment]
Closing per https://github.com/omeka/plugin-Editorial/issues/60#issuecomment-288513430
