### ISSUE TITLE
Testing latest changes

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#60]
Following trying to fix #58 from @sheilabrennan , there has been a lot of refactoring. So, going through all of the various steps for what to do with Editorial -- add an Editorial Block, reply, add access to other, check emails, and especially deleting things -- needs another run-through. Lots of blocks of different types and reordering them and deleting them will also push the boundaries and look for breaks. As always, trying to break it with weird combinations of actions is helpful (just try to remember what you did so you can include it in the steps to reproduce in the bug report! )

Use the `response-handling` branch of Editorial, and master of ExhibitBuilder.

UPDATE: NB -- There will also be an update to the plugin on that branch, so when you switch branches go to the plugins page to update it.

**Comment by mebrett** [comment]
@omeka/omekatesters Looks like it will need to be all hands here. Let's talk on Tuesday morning.

**Comment by jannellelegg** [comment]
Testing team unable to reproduce the issue in #58.  Adding, reordering, and deleting blocks did not cause any content problems and all appear to have saved appropriately.
