### ISSUE TITLE
User Permissions- access and email for Admins

### ISSUE THREAD

**Issue by jannellelegg** [omeka/plugin-Editorial#63]
When users grant access to a Editorial Block to an Admin and include Admin in the list of email recipients, the Admin can view and comment on the block- but she is unable to include herself in the list of recipients. 

![screen shot 2017-03-29 at 11 00 15 am](https://cloud.githubusercontent.com/assets/5897725/24461609/a6d16a4c-146f-11e7-81fe-bc1c47e7bdeb.png)

[In the attached photo: Alyssa (Exhibit Contrib) initiated an EB, granted access to Jessica (Admin) and Laura (Researcher). All received an email appropriately. Jessica clicked the link, added a comment, and attempted to send an email to all 3 users. Jessica was unable to include herself in the list of recipients. Both Alyssa and Laura are able to add/remove Jessica as an email recipient.]

**Comment by patrickmj** [comment]
Latest on `response-handling` should have this fixed. Pulling it down and just reloading the page should fix the email options for Jessica -- testing that it works without futzing with new blocks and permissions should be sufficient.

**Comment by jannellelegg** [comment]
And it works with no issues!

**Comment by patrickmj** [comment]
Hooray!
