### ISSUE TITLE
AdminTheme: Block Options need to be updated to access content

### ISSUE THREAD

**Issue by sharonmleon** [omeka/plugin-Editorial#65]
![Screen Shot 2021-08-17 at 4 55 51 PM](https://user-images.githubusercontent.com/741480/129799585-41917a3c-cb60-436c-86fb-2f3629f8fc8d.png)

**Comment by kimisgold** [comment]
Ready for a look on the `new-admin-theme` branch.

**Comment by sharonmleon** [comment]
All good
